dataset_params:
  dataset: 'imagenet'
  img_size: 224
  batch_size: 2048
  num_workers: 8
  data_path: /dev/shm/imagenet/train
  val_data_path: /dev/shm/imagenet/val

model:
  seed: 61
  optim_params:
    learning_rate: 0.05
    momentum: 0.9
    weight_decay: 0.0001
  params:
      dim: 2048
      pred_dim: 512
      out_dim: 2048
  num_classes: 1000
  checkpoint_path: /home/muhammetcan/checkpoints/simsiam.pkl
  linear_eval_checkpoint_path: /home/muhammetcan/checkpoints/lineareval.pkl
  epochs: 100

wandb:
  project: 'SimSiam'
  name: 'SimSiam imagenet'